### ISSUE TITLE
rotation: CW renderer considers self-axis always to be on the surface of a letter

### ISSUE THREAD

**Issue by shadoof** [wphicks/Writing3D#105]
regardless of the depth of the letter, whereas W3D treats the extruded letter as an object and finds it's axes on that basis.
* reproduce by comparing (Y-axis rotation) behavior of `sample__0_start_button.xml` in the two renderers.

W3D does the right thing IMO, but we will need a flag to allow 'CW style text object rotations' so that legacy projects display as-composed. @wphicks Let's discuss this Will.

**Comment by wphicks** [comment]
Ah, right. I know exactly why we're seeing the current behavior. My suggestion is that we add a "legacy" flag to the global options that (for now) defaults to true. If set, it will guarantee that this and other behaviors approximate (as closely as possible) the legacy cwapp. Otherwise, it will default to more "sensible" choices.

Come to think of it, we might just add a "version" flag to the global options to handle archiving even with future changes to Writing3D.

Let me know what you want, @shadoof, and I'll make it happen. This should be a pretty easy change.

**Comment by shadoof** [comment]
I agree that a version flag @wphicks would be the way to go, although because it's more memorable, I would favor a flag that is also a mnemonic, e.g. "cw2.x" for all projects intended to be legacy compliant, then "w3dx.x" for subsequent versions (where x = a digit).

**Comment by wphicks** [comment]
I agree entirely. I'll make that change as soon as I can.

**Comment by shadoof** [comment]
@wphicks This is also demo'd clearly in the new samples_17_rotation.xml pushed to the "samples_debugging" branch of w3d_samples.

**Comment by wphicks** [comment]
Definitely related to #104.

**Comment by shadoof** [comment]
@wphicks I have tested from the `develop` branch and thanks Will, rotation is now done in w3d as it was done in CW. I guess, down the line, we will still have to provide a flag that allows the more 'rational' around-self-axis rotation for extruded text objects that w3d initially offered.
