### ISSUE TITLE
Position difference between old and new software

### ISSUE THREAD

**Issue by cqx931** [wphicks/Writing3D#112]
[Example 1](https://github.com/shadoof/w3d_samples/blob/samples_debugging/sample_24a_fontPosition_floor.xml): A font object that is placed at (0,0,0), relative to Floorwall:

In old software:
![image](https://user-images.githubusercontent.com/3056154/31678694-eb975918-b33c-11e7-90b6-53830c7a3e5a.png)

In new software:
![image](https://user-images.githubusercontent.com/3056154/31678697-edb9bf88-b33c-11e7-9c68-eee1652b056d.png)
<hr>

[Example2](https://github.com/shadoof/w3d_samples/blob/samples_debugging/sample_24b_fontposition_left.xml)
For similar example relative to left/right/front wall, the position is almost the same except a slight difference in y axis.

In old software:
![image](https://user-images.githubusercontent.com/3056154/31678848-62fee548-b33d-11e7-8817-95ab11f82421.png)

In new software:
![image](https://user-images.githubusercontent.com/3056154/31678849-659a757e-b33d-11e7-86cf-b4e04e22a55f.png)

**Comment by shadoof** [comment]
@cqx931 @wphicks Hi Sally, many thanks for making samples carefully like this!

In this case, however, you were not to know that there will be *no positioning of objects relative to the walls* in the new software (because we are no longer targeting a single cube configuration for VR devices).

I'm closing this for this reason.

**Comment by cqx931** [comment]
Is there any documentation or list about things that is no longer supported for the new software?
I think it would be nice to have a wiki page for this as well as other tips you mentioned in the class(don't trust sound looping etc).

**Comment by wphicks** [comment]
@cqx931, thank you very much for the report on this, especially with such a great illustration of the issue! If only all my bug reports were so clear! I'm actually going to reopen this with the legacy flag, since supporting wall placement is very important for supporting legacy projects.

@shadoof, given the work I've already put into placement on the walls now, I don't see any *technical* reason we can't allow students to continue to use this feature, though I think you and I are in agreement that this should be discouraged from an artistic/conceptual standpoint.

@cqx931, I think documenting deprecated or temporarily unsupported features is an excellent idea (although I *think* there aren't any features that won't eventually be supported, since the goal is 100% compatibility with legacy projects). A quick off-the-top-of-my-head list that might be transferred to a wiki page:

- Stereoscopic images
- *Some* of the particle system actions
- Incorrect z-sorting of transparent objects

I think anything else that doesn't work is either a reported bug that I'm actively working on or news to me.

**Comment by wphicks** [comment]
Note to self: the placement issue against the left-wall is probably "close enough" for now and an alignment artifact. The placement issue against the floor is a genuine issue that needs to be resolved.

**Comment by shadoof** [comment]
@cqx931 @wphicks Great exchange! and I entirely agree with Will on all this.

Wiki=public-facing information/documentation. If you guys agree, I would move toward putting this kind of information onto 'pages' that are simple Google Docs bound together using Clement Valla/This is Our Work's *Binder* system. As you know I've begun. The shared folder for such pages is here:

https://drive.google.com/drive/folders/0By7izea0dXGyRG92akpHUzZNWXM?usp=sharing

To make a new page, duplicate one of the existing pages, add content and then (for now) contact me and suggest where/how in the current hierarchy of writing3d.xyz you think this page should appear.

(Justification: a) editing content for pages is very easy and straightforward, b) I will be obliged to take some editorial and organization responsibility for the pages and the site.)

**Comment by wphicks** [comment]
I think that's an optimal use of Binder, since it will be very easy for students to contribute regardless of technical skills. I'm going to continue to take a hands-off approach on the documentation there, but feel free to scrape anything I post to the developer-facing docs into there if it will be of use to students.

**Comment by wphicks** [comment]
Huge thank you on this one, @cqx931! Was just able to fix this up in about 5 minutes, thanks to your fine samples. Change should be merged into master by the end of the night.
