### ISSUE TITLE
Install fails with --user flag on Homebrew Python

### ISSUE THREAD

**Issue by wphicks** [wphicks/Writing3D#32]
This appears to be a known bug due to a system-level distutils.cfg file essentially setting the --prefix option for all installs. Obviously, --prefix and --user cannot be specified together, so the install fails.

Documentation should be updated to warn Homebrew users, and install_w3d.py installer tool should detect Homebrew installs and drop the --user flag.

@purvigoel, can you confirm this and provide further detail?

**Comment by purvigoel** [comment]
It was indeed Homebrew Python that was being used, so I believe it does appear that caused the issue. After running python3 setup.py install --user --force --prefix=, installation seemed to work. However, there was an issue with Blender that I wanted to pass by you. The script appeared to reinstall blender rather than find the one already installed by the blender installer. The installed blender didn't seem to appear in the $PATH within a shell. 
I seem to remember something similar happening with me, but I'm not entirely sure. Just wanted to put this by you in case.

**Comment by wphicks** [comment]
So, to confirm, after installing with an empty prefix flag, the pyw3d module _is_ available from a python3 prompt? Can the samples be run?

In terms of installing a separate version, that's working as intended unless you also supplied the --blenderdir flag to setup.py. Run `python3 setup.py install --help` for more info. This is related to issue #27, so I'll continue the discussion there.

**Comment by purvigoel** [comment]
Just confirmed it--the installation definitely worked after running the empty prefix tag, as did running the samples.

**Comment by wphicks** [comment]
Documentation (and install_w3d.py) updated through ea9e83ed2a9c3c38f0229d6a4a6463eeb2657a49.
