### ISSUE TITLE
Pivot point for text rotation needs to move to center

### ISSUE THREAD

**Issue by shadoof** [wphicks/Writing3D#61]
Shows very clearly that something is awry. Check:
* handling of around self-axis. (We do need clear best practices and defaults for this that are compatible)
Note:
* there seems to be a problem with the way W3D renders text that overlaps with an image (regardless of z) after a rotation (after clicking 'Front Link' in this case - also check sample 02 for this). Part of the text object that is in front of the rotated image is sometimes *not* rendered.

**Comment by shadoof** [comment]
There is a new sample, 09, that allows this to be tested more easily.

**Comment by wphicks** [comment]
Oof, yes. The self-axis for text is not currently handled properly at all. A clear mistake on my part.

[StackOverflow reference for self](https://blender.stackexchange.com/questions/5519/setting-the-pivot-point-of-an-object)

As for the second bullet point, I'm not seeing this behavior for either sample. If someone has a screenshot, I'll try to run down if something platform-specific is going on.

**Comment by wphicks** [comment]
Oh, and if you do have a screenshot, please spin that off into a new issue titled "Images interfere with text rendering after overlap"

**Comment by wphicks** [comment]
Fixed the "around-self-axis" issue. In general, new users should be advised to use this flag whenever possible, since it makes for a well-defined, consistent rotation axis. It wouldn't be too hard to mimic the CW app behavior when this option is switched off, but someone would need to do some testing to determine what the rules are for the rotation point in this case.
